class profile {
  include backup
  include bashgitprompt
  include bashrc
  include dejadup
  include dropbox
  include gedit
  include gimp
  include gitg
  include gitrepos
  include gnometerminal
  include gnometweaktool
  include googlechrome
  include gpg
  include icedteaweb
  include infinality
  include keepassx
  include manheimpuppetrepos
  include manheimvpn
  include pdfmerge
  include pidgin
  include profile
  include seahorse
  include sshkeys
  include sudoers
  include syntastic
  include thunderbird
  include tig
  include vim
  include virtualization
}
